Name: Sri Harsha Kacharla
Student Id: 002556509

1: Write a function that finds the factorial of a number. Test the function finding the factorial of the number 10

In [11]:
def fact(number):
  result = 1
  if number < 0:
    print("Number less than 0")
  elif number == 0:
    print(1)
  else:
    for n in range(1,number+1):
      result = result * n
  print(result)

fact(10)

3628800


2: Write a function that determines if a number is a prime number. Test the function with
the following numbers: 3 and 1251.

In [20]:
def findPrime(number):
  if number > 1:
    for n in range(2, number):
      if (number % n) == 0:
        print(number, "is not a prime number")
        break
    else:
      print(number, "is a prime number")
  else:
    print(number, "is not a prime number")

findPrime(3)
findPrime(1251)

3 is a prime number
1251 is not a prime number


3: Write a function that transposes a matrix. Test with a 3 x 3 identity matrix.


In [24]:
def transpose(matrix):
  result = [[0,0,0],
         [0,0,0],
         [0,0,0]]
  for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        result[j][i] = matrix[i][j]
  for r in result:
    print(r)
matrix = [[1,2,3],
    [4,5,6],
    [7,8,9]]

transpose(matrix)


[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


4: Using Pandas and Numpy, write a piece of code to combine two series into one. Test your code with: 
np.random.seed(0) 
series1 = pd.Series(np.arange(10))
series2 = pd.Series(np.arange(26))
Do not forget to set the seed, or your answer won’t be reproducible

In [25]:
import pandas as pd
import numpy as np


def combineSeries(series1, series2):
    firstList = series1.values.tolist()
    secondList = series2.values.tolist()
    print(pd.Series(firstList + list(set(secondList) - set(firstList))))


np.random.seed(0)
series1 = pd.Series(np.arange(10))
series2 = pd.Series(np.arange(26))
combineSeries(series1, series2)


0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64


5: Using pandas, write a piece of code to convert the first character of each element in a series to uppercase. Test your code with:

series = pd.Series(['nlp', 'will', 'be', 'easy?'])

In [28]:
def toUpper(series):
    for x in range(0,series.size):
        series[x] = series[x][0].upper()+series[x][1:]
    print(series.values)

series = pd.Series(['nlp', 'will', 'be', 'easy?'])

toUpper(series)

['Nlp' 'Will' 'Be' 'Easy?']


Bonus: Using pandas, write a piece of code to get the frequency of unique values in the
entire dataframe (not using built in functions). Test your code with:
dataFrame = pd.DataFrame(np.random.randint(5, 10, 20).reshape(-1, 4), columns = list('abcd'))

In [32]:
import pandas as pd
import numpy as np
def frequency(dataFrame):
    totalFreq = list()
    totalRepeated = list()
    for x in dataFrame.values:
        freq = list()
        repeated = list()
        print(x)
        for y in x:
            if(totalFreq.__contains__(y)):
                totalFreq.remove(y)
                totalRepeated.append(y)
            else:
                if not totalRepeated.__contains__(y):
                    totalFreq.append(y)
            if(freq.__contains__(y)):
                freq.remove(y)
                repeated.append(y)
            else:
                if not repeated.__contains__(y):
                    freq.append(y)
        print("local freq:"+str(len(freq)))
    print("total freq:" + str(len(totalFreq)))


dataFrame = pd.DataFrame(np.random.randint(5, 10, 20).reshape(-1, 4), columns=list('abcd'))
frequency(dataFrame)

[7 8 5 8]
local freq:2
[9 6 7 9]
local freq:2
[8 9 9 9]
local freq:1
[8 9 9 9]
local freq:1
[5 9 8 7]
local freq:4
total freq:1
