<a href="https://colab.research.google.com/github/srikacharla/CSC8980/blob/main/HomeWork2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name**: Sri Harsha Kacharla
**Student Id**: 002556509

1. Create a cosine similarity matrix for all of Shakespeare’s works found in the provided file. This will result in a 42 by 42 matrix with the cosine similarity between each of his works. In other words, calculate the document-wise cosine similarity between all of Shakepeare’s works. (50 points). ​Use TF_IDF for this. Note, you can use the Cosine Similarity function on scikit-learn or implement your own, but no other library/package is allowed.


In [362]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import linear_kernel
import os
import numpy as np

In [363]:
txt_files = os.listdir('Shakespeare')
data = []
for file in txt_files:
   data.append(open(os.path.join('Shakespeare',file), 'r').read())

In [364]:
tfidf = TfidfVectorizer().fit_transform(data)

In [365]:
cosineMatrix = cosine_similarity(tfidf, tfidf)
print(cosineMatrix)


[[1.         0.59813572 0.65459176 ... 0.52515851 0.57395169 0.69694474]
 [0.59813572 1.         0.66801609 ... 0.5890345  0.59258345 0.71771293]
 [0.65459176 0.66801609 1.         ... 0.59895863 0.66716633 0.79038899]
 ...
 [0.52515851 0.5890345  0.59895863 ... 1.         0.52277672 0.62033426]
 [0.57395169 0.59258345 0.66716633 ... 0.52277672 1.         0.70530628]
 [0.69694474 0.71771293 0.79038899 ... 0.62033426 0.70530628 1.        ]]


2. Write a function that takes the previous matrix and a number ​n​ as parameters (nothing else will be accepted) and return the top ​n​ similar works. Use the function to output the top 10 similar works. (30 points).


In [366]:
def findSimilarity(cosineMatrix, n):
   for i in range(len(cosineMatrix)):
      cosineMatrix[i][i] = 0
   x, y = np.unravel_index(cosineMatrix.flatten().argsort()[-2*n:], cosineMatrix.shape)
   x = np.flip(x)
   y = np.flip(y)
   result = []
   for i in range(0, len(x), 2):
      x1 = x[i]
      y1 = y[i]
      if x1 != y1:
         result.append((x1, y1, cosineMatrix[x1][y1]))
   return result

findSimilarity(cosineMatrix,10)

[(12, 32, 0.9175430138884021),
 (16, 2, 0.9076165568984123),
 (18, 32, 0.8677688748875242),
 (24, 6, 0.8437915980298416),
 (35, 36, 0.8389525010107527),
 (12, 18, 0.8381452108269781),
 (41, 5, 0.8363042342905285),
 (38, 24, 0.8354926670186541),
 (24, 35, 0.8343507770652858),
 (3, 5, 0.8342954531999516)]

3. Using the code from the Language Models II class, train two simple language models using all of the files (together) in shakespeares-works_TXT_FolgerShakespeare.zip. One model should be trained using bigrams, the other using trigrams. (40 points).

In [367]:
import nltk
from nltk import bigrams, trigrams
from collections import defaultdict
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [368]:
tokens = []
for doc in data:
  tokens.append(nltk.word_tokenize(doc))

In [369]:
##bigrams
modelB = defaultdict(lambda: defaultdict(lambda: 0))
for sentence in tokens:
    for w1, w2 in bigrams(sentence, pad_right=True, pad_left=True):
        modelB[(w1,)][w2] += 1

for w1 in model:
    total_count = float(sum(modelB[(w1,)].values()))
    for w2 in modelB[(w1,)]:
        modelB[(w1,)][w2] /= total_count

In [370]:
dict(modelB[("we",)])

{'!': 0.0007112375533428165,
 "'ll": 0.05334281650071124,
 "'re": 0.00035561877667140827,
 '(': 0.00035561877667140827,
 ',': 0.018847795163584636,
 '--': 0.0007112375533428165,
 '.': 0.005689900426742532,
 ';': 0.00035561877667140827,
 '?': 0.0035561877667140826,
 'A': 0.00035561877667140827,
 'Abroad': 0.00035561877667140827,
 'Almost': 0.00035561877667140827,
 'Are': 0.00035561877667140827,
 'Be': 0.00035561877667140827,
 'Beaufort': 0.00035561877667140827,
 'Caesar': 0.00035561877667140827,
 'Cave': 0.00035561877667140827,
 'Commune': 0.00035561877667140827,
 'Determine': 0.00035561877667140827,
 'Do': 0.00035561877667140827,
 'Few': 0.00035561877667140827,
 'Have': 0.0010668563300142249,
 'King': 0.00035561877667140827,
 'May': 0.00035561877667140827,
 'Must': 0.0007112375533428165,
 'Our': 0.00035561877667140827,
 'Salisbury': 0.00035561877667140827,
 'Shall': 0.00035561877667140827,
 'Should': 0.00035561877667140827,
 'That': 0.00035561877667140827,
 'The': 0.0007112375533428165

In [371]:
##Trigram
modelT = defaultdict(lambda: defaultdict(lambda: 0))

# Count frequency of co-occurence
for sentence in tokens:
    for w1, w2, w3 in trigrams(sentence, pad_right=True, pad_left=True):
        modelT[(w1, w2)][w3] += 1

# Let's transform the counts to probabilities
for w1_w2 in modelT:
    total_count = float(sum(modelT[w1_w2].values()))
    for w3 in modelT[w1_w2]:
        modelT[w1_w2][w3] /= total_count


In [372]:
dict(modelT[tuple(["master","of"])])

{'.': 0.047619047619047616,
 'a': 0.09523809523809523,
 'all': 0.047619047619047616,
 'fence': 0.047619047619047616,
 'high': 0.047619047619047616,
 'his': 0.19047619047619047,
 'it': 0.047619047619047616,
 'mine': 0.047619047619047616,
 'my': 0.14285714285714285,
 'the': 0.14285714285714285,
 'thy': 0.047619047619047616,
 'what': 0.047619047619047616,
 'your': 0.047619047619047616}

4. Write a function that takes the following three parameters: model, list of start words, number of sentences to generate. This function should return the sentences generated as a list. DO NOT print anything to the screen from within the function. Use this function to generate 10 sentences with the bigram model from the previous question, and 5 sentences with the trigram model from the previous question. (30 points)

In [373]:

def gen_sentences(model,start_words,num_sentences):
  sentences = []
  length = -len(start_words)
  for i in range(num_sentences):
    text = start_words
    sentence_finished = False

    while not sentence_finished:
      # select a random probability threshold  
      r = random.random()
      # print("random", str(r))
      # print("text",text)
      accumulator = .0
      # print("len",str(length))
      # print("abc ",model[tuple(text[length:])].keys())
      for word in model[tuple(text[length:])].keys():
          # print(model[tuple(text[length:])].keys())
          # print(model[tuple(text[length:])][word])
          accumulator += model[tuple(text[length:])][word]

          # select words that are above the probability threshold
          if accumulator >= r:
              # print(word)
              text.append(word)
              break
          # print(text)


      if text[length:] == [None, None][length:]:
          sentence_finished = True
      # sentence_finished =True
      
    sentences.append(' '.join([t for t in text if t]))
  return sentences

In [379]:
import random

sentencesTrigram = gen_sentences(modelT,['Edited','by'],5)
print((sentencesTrigram))


["Edited by Barbara A. Mowat and Paul Werstine with Michael Poston and Rebecca Niles Folger Shakespeare Library https : //shakespeare.folger.edu/shakespeares-works/the-two-noble-kinsmen/ Created on Jul 31 , 2015 , from FDT version 0.9.2.1 Characters in the town . He kisses her . QUEEN ELIZABETH And wilt thou have thy head is off . ] This comes too short to hit . LAERTES Alas , I thee . APEMANTUS Thou liest . STEPHANO That shall I say so . [ Attendant exits . ] But I am on the tabor to the King . 'T is very well met . By this sun that looks upon ( Be it so In favor 's good indeed . If he were , a nightwatch constable , it is your native spring ; For `` Certes , she 's big with tears and hear the will , sir , and his penance , wandered through the street , With gentle travail , not for such a blessing against his valor , for I was in this desert place -- As I return his sworn brother to the end try the argument of your children will he do , to London sent The heads are brought together .

In [387]:
sentencesBigram = gen_sentences(modelB,["Edited"],10)
print(len(sentencesBigram))
print(sentences)


10
["we are politicians , Malvolio's a Peg-a-Ramsey , and that 's Palamon . Arcite is gently visaged , yet stands off In differences so mighty . If thou wert a king and all his valiant parts Did not the first and dearest of your royal person , Nor wink , Which , of my time to come , I 'll move me . '' LADY MACBETH There 's some other business . We coldly pause for that , Malvolio ? MALVOLIO Madam , within these arms in assurance My body shall make your loves . So to offend no man is there no other tribute at thy solemn feast , of most disastrous chances : Of Caesar 's arm That he may creep in at the fingers ' ends for flap-dragons , and therefore keep it. -- 'T is a prohibition so divine a temple to commix With winds that held the right , do you mark me . It is a dear manikin to you . CERES Tell me , that that ring . There is no comfort To give me thanks for that love of Valentine , I subscribe not that my angel be turned outward ! VIOLA Who governs here ? STANLEY Madam , he should not

Bonus (20 points): Using the same methodology from questions 1 and 2, create a similarity matrix between the 20 newsgroups corpus. And find the top 5 similar newsgroups.


In [375]:
from sklearn.datasets import fetch_20newsgroups
twentyNewsgroupsData = fetch_20newsgroups()
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(twentyNewsgroupsData.data)
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(cosine_sim)



[[1.         0.04405974 0.11017033 ... 0.04433678 0.04457107 0.0329325 ]
 [0.04405974 1.         0.06242113 ... 0.07373268 0.06959306 0.02439956]
 [0.11017033 0.06242113 1.         ... 0.07569182 0.06214891 0.02357985]
 ...
 [0.04433678 0.07373268 0.07569182 ... 1.         0.02909961 0.00716986]
 [0.04457107 0.06959306 0.06214891 ... 0.02909961 1.         0.02428174]
 [0.0329325  0.02439956 0.02357985 ... 0.00716986 0.02428174 1.        ]]


In [376]:
similar_works = findSimilarity(cosine_sim,5)
print(similar_works)

[(10777, 2002, 1.0000000000000002), (5392, 14, 1.0000000000000002), (9989, 800, 1.0), (4495, 4772, 0.9997809868890166), (8665, 4772, 0.9996809512865921)]
